# Generated by Django 5.2.18 on 2026-10-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_accesapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonetampon',
            name='places_liberes',
            field=models.JSONField(default=list, verbose_name="Places d'origine de la réservation"),
        ),
    ]
