# Generated by Django 5.2.18 on 2026-10-09 07:23

import django.db.models.deletion
import django.utils.timezone
import uuid
import wagtail.fields
import wagtail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('statut', models.CharField(choices=[('actif', 'Abonné'), ('attente', 'En attente de confirmation'), ('desinscrit', 'Désinscrit')], default='actif', max_length=12, verbose_name='Statut')),
                ('source', models.CharField(choices=[('formulaire', 'Formulaire du site'), ('admin', 'Ajout manuel (admin)')], default='admin', max_length=12, verbose_name='Origine')),
                ('jeton', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Sert aux liens de désinscription et de confirmation.', unique=True, verbose_name='Jeton personnel')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inscrit le')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('date_desinscription', models.DateTimeField(blank=True, null=True, verbose_name='Désinscrit le')),
            ],
            options={
                'verbose_name': 'Abonné',
                'verbose_name_plural': 'Abonnés',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Pour vous repérer dans l'admin (ex : Newsletter d'octobre 2026).", max_length=150, verbose_name='Titre interne')),
                ('objet', models.CharField(help_text='Ce que les destinataires voient dans leur boîte de réception. Court et précis.', max_length=150, verbose_name="Objet de l'e-mail")),
                ('preheader', models.CharField(blank=True, help_text="Phrase affichée après l'objet dans la plupart des messageries.", max_length=150, verbose_name="Texte d'aperçu")),
                ('salutation', models.CharField(blank=True, default='Bonjour {prenom},', help_text="{prenom} est remplacé par le prénom de l'abonné (ou retiré s'il est inconnu). Laisser vide pour ne pas en mettre.", max_length=100, verbose_name="Formule d'appel")),
                ('contenu', wagtail.fields.StreamField([('titre', 0), ('texte', 1), ('image', 7), ('bouton', 12), ('actualites', 15), ('page_en_avant', 21), ('encadre', 24), ('separateur', 25)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Titre'}), 1: ('newsletter.blocks.TexteBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Décrit l'image pour les personnes qui ne la voient pas (images bloquées, lecteur d'écran). Vide : la description ou le titre de l'image est utilisé.", 'label': 'Texte alternatif', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Légende (facultatif)', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('pleine', 'Toute la largeur'), ('moyenne', 'Moyenne, centrée'), ('petite', 'Petite, centrée')], 'label': 'Largeur'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Lien au clic (facultatif)', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt', 3), ('legende', 4), ('largeur', 5), ('lien', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'max_length': 60}), 9: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page du site', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'label': 'Ou adresse externe', 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('dore', 'Doré (principal)'), ('bordeaux', 'Bordeaux')], 'label': 'Couleur'}), 12: ('wagtail.blocks.StructBlock', [[('texte', 8), ('page', 9), ('url', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Nos dernières actualités', 'label': 'Titre', 'required': False}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': "Nombre d'actualités", 'max_value': 6, 'min_value': 1}), 15: ('wagtail.blocks.StructBlock', [[('titre', 13), ('nombre', 14)]], {}), 16: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page à mettre en avant'}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Titre (vide : titre de la page)', 'required': False}), 18: ('wagtail.blocks.TextBlock', (), {'label': 'Texte (vide : résumé de la page)', 'required': False}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': "Image (vide : image de la page s'il y en a une)", 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'En savoir plus', 'label': 'Texte du bouton'}), 21: ('wagtail.blocks.StructBlock', [[('page', 16), ('titre', 17), ('texte', 18), ('image', 19), ('texte_bouton', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': False}), 23: ('newsletter.blocks.TexteBlock', (), {'label': 'Texte'}), 24: ('wagtail.blocks.StructBlock', [[('titre', 22), ('texte', 23)]], {}), 25: ('newsletter.blocks.SeparateurBlock', (), {})}, verbose_name='Contenu')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'Envoi en cours'), ('envoyee', 'Envoyée')], default='brouillon', editable=False, max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('date_envoi', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Envoyée le')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-date_creation'],
                'permissions': [('envoyer_newsletter', 'Peut envoyer une newsletter aux abonnés')],
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=10)),
                ('date_lancement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('derniere_erreur', models.TextField(blank=True)),
                ('lance_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='newsletter.newsletter')),
            ],
            options={
                'verbose_name': 'Envoi',
                'ordering': ['-date_lancement'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('titre_bandeau', models.CharField(default='Restez informés', help_text="Grand titre affiché sur l'image, comme sur la page d'accueil.", max_length=120, verbose_name='Titre du bandeau')),
                ('sous_titre', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre du bandeau')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Ce que contient la newsletter, sa fréquence…', verbose_name='Présentation')),
                ('titre_formulaire', models.CharField(default='Inscrivez-vous à notre newsletter', max_length=120, verbose_name='Titre du formulaire')),
                ('texte_consentement', models.CharField(default="J'accepte de recevoir la newsletter de La Concorde asbl. Je peux me désinscrire à tout moment.", max_length=255, verbose_name='Texte de la case de consentement')),
                ('message_succes', models.CharField(default='Merci ! Votre inscription est enregistrée.', max_length=255, verbose_name='Message après inscription')),
                ('confirmation_par_email', models.BooleanField(default=False, help_text="Recommandé : l'inscription n'est active qu'après un clic sur le lien reçu par e-mail. Évite les inscriptions d'adresses de tiers et prouve le consentement.", verbose_name='Demander une confirmation par e-mail (double opt-in)')),
                ('image_bandeau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image du bandeau')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': "Page d'inscription à la newsletter",
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('a_envoyer', 'À envoyer'), ('envoye', 'Envoyé'), ('echec', 'Échec'), ('ignore', 'Non envoyé (désinscrit ou annulé)')], db_index=True, default='a_envoyer', max_length=10)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('erreur', models.CharField(blank=True, max_length=255)),
                ('date_envoi', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('abonne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='newsletter.abonne')),
                ('envoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='newsletter.envoi')),
            ],
            options={
                'verbose_name': 'Livraison',
                'constraints': [models.UniqueConstraint(fields=('envoi', 'email'), name='newsletter_livraison_unique')],
            },
        ),
    ]
